2025-09-04 14:45:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 14:47:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 14:54:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 15:08:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 15:09:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 15:21:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 16:06:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 16:16:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 17:15:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 17:17:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 19:11:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 19:29:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 19:47:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 19:49:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 22:41:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 22:47:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-04 22:49:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 01:13:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 02:20:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 09:25:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 09:48:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 10:16:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 10:33:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 12:18:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 13:28:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 13:31:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 13:32:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-05 19:50:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Index "IDX_USER" already exists; SQL statement:
CREATE INDEX idx_user ON axir_backups (userId) [42111-214]
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:223)
	at AxInventoryRestore-3.8.2.jar//org.h2.message.DbException.get(DbException.java:199)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.ddl.CreateIndex.update(CreateIndex.java:74)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at AxInventoryRestore-3.8.2.jar//org.h2.command.Command.executeUpdate(Command.java:252)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at AxInventoryRestore-3.8.2.jar//org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.Base.setup(Base.java:113)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.database.impl.H2.setup(H2.java:34)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.AxInventoryRestore.enable(AxInventoryRestore.java:112)
	at AxInventoryRestore-3.8.2.jar//com.artillexstudios.axinventoryrestore.libs.axapi.AxPlugin.onEnable(AxPlugin.java:186)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280)
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652)
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:1583)
